### ISSUE TITLE
Possibly add subgroups/nested groups of metrics

### ISSUE THREAD

**Issue by bitprophet** [bitprophet/fullerene#2]
Use case is to have "section headers" on the larger groupings such as `baseline`, but would also be useful for other things.

Possible implementation: aliasing, i.e. define `baseline` as `disk` + `cpu` + `...`.

Expanding this idea, having both metrics and collections of metrics as objects/dicts would make this easier -- we could then optionally allow folks to give them labels/names, and then refer to those elsewhere, i.e. having the same metric path show up in multiple groups/dashboards/whatever. Something like:

```
metrics:
    group1:
        - foo.bar
        - biz.baz:
            name: bizbaz
    group2:
        - bizbaz
```

Though that feels slightly backwards in a few ways -- having the metric's key be the actual path is possibly OK, as it's a pattern we're using in exclusions (#7) but defining it inside a group and referring to it in another group is definitely wonky. 

The other obvious approach is to define metrics in one section and groups/group memberships in another -- but then that implies that perhaps _all_ metrics need to be defined in this way, so that for the simple use case of "this one metric is only used in one spot and has no metadata" you're now dealing with some boilerplatey crap.

EDIT: Actually, no -- we can do what is done for the timeperiod/from-kwarg override behavior, and simply prefilter metric paths to see if they match a defined metric name/identifier, then substitute. So metrics with metadata can be optionally defined in one config section containing only those handful of metrics that need customization; the big list o' metrics would then be a mix of one-off real paths and names referencing the metadata'd metrics. E.g.:

```
metrics:
    metric1:
        path: foo.bar.*
        excludes: [biz, baz]
groups:
    group1:
        - actual.metric.path
        - another.real.metric
        - metric1
        - blah.*
    group2:
        - metric1
```

Another note: one can accomplish referencing itself (i.e. define once, "insert" into multiple locations) in YAML natively with YAML references (or whatever they're called, the `&stuff`) but it may be worthwhile to implement this at the Python level instead so that we can make better use of the metadata.
