### ISSUE TITLE
Role/non-basic metrics

### ISSUE THREAD

**Issue by bitprophet** [bitprophet/fullerene#21]
Need a way to assert that e.g. database servers should display additional metric paths over the 'baseline' metric group, such as postgres lag or whatnot.

This is partially served by having "wide ranging" metrics in the baseline (such as `df`) and then using the `exclude` feature to trim things down; thus a DB server will already display its DB partition information.

So we could solve this by padding out `baseline` with all possibly useful metrics and just ensure that if a host lacks a metric, we don't try to show it.

Otherwise, we need a way to associate hosts with optional extra metrics, meaning another config chunk that maps hostnames to metric lists. Not hard, if config-generated; anything hand-oriented might need to allow keying off hostname/globbing/etc.

**Comment by bitprophet** [comment]
Had to put in some stuff to patch up `combine()` (it isn't able to do "correct" expansion when given >1 glob -- another reason to strongly consider moving some of this stuff into Graphite itself as a web hook) and with that in place I can e.g. drop a complicated haproxy metric into baseline and it still only shows up on systems that have it.

So for now I think this can be handled just by adding a wide net of desired metrics to whatever metric group you want, and they'll naturally show up or be hidden depending on the system in question.

**Comment by bitprophet** [comment]
Had a thought -- this might be best implemented as an inverse: assume that you want a view of most metrics in the system and just want to filter out a few.

A little config tweaking could make this possible by leveraging `Graphite.query_all`, if we reworked `groups` a bit:

```
metrics:
  foo:
  bar:
metric_groups:
  baseline:
    title: "Basic overview"
    include:
      - explicitly
      - listed
      - metrics
      - as usual
  nearly_everything:
    title: "All interesting metrics"
    exclude:
      - just
      - a
      - few
      - things
```
