### ISSUE TITLE
Host-group graph pages

### ISSUE THREAD

**Issue by bitprophet** [bitprophet/fullerene#5]
Right now we have pages displaying e.g. disk-related graphs for a single host, and pages displaying a bunch of various graphs, again per host.

Think about how best to slice this the other way and allow viewing a group of hosts' graphs at once.

Potential groups:
- All hosts for a given website, i.e. if one has multi-tenancy on a collection of servers, you don't just want "servers 1-3", you want "all servers that serve anything related to site A".
- All hosts serving a given role, e.g. web / db
- Combinations of these

Implementation could be lists of static hostnames and host patterns, in config files, with keyed names, and aliases as well (so a group can be set up that consists solely or partially of other groups.)

**Comment by bitprophet** [comment]
Can work on this now that we have basic collections support. having a list grouped per-project is great and all, but it's mostly useless without an "overview" page for the whole project.

Probably add this into the collections view -- an overview link above the list-o-hosts.

Showing all defined metrics for all hosts would probably be way too much data, even with the hand-crafted list-o-metrics, so think about ways to pare it down:
- Specific config section listing what to show on this page (i.e. "overview: [list of metrics]")
- Override the 'expansion' options for all metrics when displaying here, forcing eg disk/etc to be on one graph
  - Less graphs, but then the disk ones would probably be too busy to be useful (which is why they're defined as expanded)
- Grid view, hosts on Y axis and metrics on X axis; still requires some paring down of metrics to be usable though
- ???

I think having Yet More Config (i.e. 1st option) is probably the way to go.

**Comment by bitprophet** [comment]
Yet More Config is a good start; I think also experimenting with smaller graph sizes (on a grid, too, as above) will help.

Also note that this should (probably) really turn into a very simple 2x combo of hosts and metrics, possibly by splitting up the values of `collections`' items -- so it's not just lists of hosts, but lists of hosts paired with lists of metrics.

This forms one potential solution to #21: for a specific role, you just make a new collection for the role, have its host list be all hosts fulfilling that role, and the metric list only the metric or metrics specific to those roles. E.g.:

```
collections:
    by_role:
        title: "By role"
        groups:
            db:
                hosts:
                    - db1.example.com
                    - db2.example.com
                metrics:
                    - replication_lag
                    - postgres_data_partition_free_space
                    - postgres_active_connections
```
