### ISSUE TITLE
Statically defined groups of hosts

### ISSUE THREAD

**Issue by bitprophet** [bitprophet/fullerene#9]
I.e. allow navigational elements not derived from the dynamic host list that comes out of introspecting Graphite.

Perhaps a top level page that is just nav links to the automatic index and then some top level set of collections, where (in the same all-in-one YAML we've been using so far) one might have this:

```
collections:
  by-project:
    giantbomb:
        - web6.giantbomb.com
        - web7.giantbomb.com
        - redis10.whiskeymedia.com
        - lb2.whiskeymedia.com
    comicvine:
        - web5.comicvine.com
        - redis10.whiskeymedia.com
        - lb2.whiskeymedia.com
  by-class:
    db:
        - db.giantbomb.com
        - db.comicvine.com
    web:
       - web6.giantbomb.com
       - ...
```

So the top level page would have 3 links: `automatic`, `by-project`, `by-class`, with `by-project` and `by-class` generated by one's config management or by hand.
